#!/bin/sh


# Terminal
alt + Return
	kitty -1 --listen-on unix:/tmp/kitty-sock

alt + w
	$BROWSER

alt + r
	set-bg

alt + d
	rofi -combi-mode -show run

alt + m
    sp music

alt + n
    sp notes

XF86AudioPlay
	mpc toggle

XF86AudioNext
	mpc next

XF86AudioPrev
	mpc prev

XF86AudioRaiseVolume
	pulseaudio-ctl up 2

XF86AudioLowerVolume
	pulseaudio-ctl down 2

