#!/bin/sh


# Terminal
alt + Return
	$TERMINAL

alt + w
	$BROWSER

alt + r
	set-bg

alt + d
	rofi -combi-mode -show run

alt + m
    sp ncmpcpp
    

XF86AudioPlay
	mpc toggle

XF86AudioNext
	mpc next

XF86AudioPrev
	mpc prev

XF86AudioRaiseVolume
	pulseaudio-ctl up 2

XF86AudioLowerVolume
	pulseaudio-ctl down 2

