directory: /media/music
import:
    move: yes
    write: yes
    log: beetslog.txt
art_filename: albumart
plugins: bpd ftintitle lastgenre hook edit
ftintitle:
    auto: true
lastgenre:
    canonical: yes
    fallback: "Unknown"
hook: 
  hooks:
    - event: item-imported
      command: mpc update && echo "Updated MPD"
pluginpath: ~/beets/myplugins
ui:
    color: yes
paths:
    default: $artist/$album/$track $title
    singleton: $artist/singles/$title
    comp: /"Various Artists"/$track $title
