#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.6

bsp-layout set tall 1

bspc rule -a Brave-browser desktop=^2

bspc config external_rules_command $XDG_CONFIG_HOME/bspwm/brave-rule
