#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a brave desktop='^2'
bspc rule -a Steam state=floating floating=on follow=on

# Scratch pads
bspc rule -a Music sticky=on state=floating hidden=on
kitty -o remember_window_size='no' -o initial_window_width=800 -o initial_window_height=500 --class Music --title Music -e ncmpcpp &
