#! /bin/sh

bspc config border_width        0
bspc config window_gap          12

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config split_ratio          0.5

bspc rule -a Brave-browser desktop=^2
bspc rule -a sxiv state=floating

bspc rule -a music-sp state=floating rectangle=1100x600+200+240
bspc rule -a feh-sp state=floating rectangle=350x350+1050+350

bspc config external_rules_command $XDG_CONFIG_HOME/bspwm/brave-rule
bspc config external_rules_command $XDG_CONFIG_HOME/bspwm/sp-rule
