#!/bin/sh

# Kill running polybars
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $(id -ru) -x polybar >/dev/null; do sleep 1; done

# Launch Polybar, using default config location ~/.config/polybar/config
polybar bottom-bar &
